name: Android CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-app-${{ github.sha }}
          restore-keys: |
            gradle-
            
      - name: Build apk with Gradle
        run: bash ./gradlew assembleRelease
        
      - name: Build bundle with Gradle
        run: bash ./gradlew bundleRelease
        
      - name: Sign apk release
        if: success()
        id: sign_apk
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "31.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Sign bundle release
        if: success()
        id: sign_bundle
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "31.0.0"
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: log all info
        with: 
          run: |
            ls app/build/outputs/apk/release/
            ls app/build/outputs/bundle/release
      - name: Publish release.
        if: success()
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            ${{steps.sign_apk.outputs.signedReleaseFile}}
            ${{steps.sign_bundle.outputs.signedReleaseFile}}
            app/build/outputs/mapping/release/mapping.txt
